# Generated by Django 6.0.4 on 2026-07-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_load_hardening'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusbuilding',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Kampus binosi', 'verbose_name_plural': 'Kampus binolari'},
        ),
        migrations.AlterModelOptions(
            name='coursesyllabus',
            options={'ordering': ['sort_order', 'subject_name'], 'verbose_name': 'Fan syllabus katalogi', 'verbose_name_plural': 'Fan syllabus katalogi'},
        ),
        migrations.AlterModelOptions(
            name='devicepairingsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Qurilma ulanishi', 'verbose_name_plural': 'Qurilma ulanishlari'},
        ),
        migrations.AlterModelOptions(
            name='livetestsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jonli test sessiyasi', 'verbose_name_plural': 'Jonli test sessiyalari'},
        ),
        migrations.AlterModelOptions(
            name='livetestsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Test javobi', 'verbose_name_plural': 'Test javoblari'},
        ),
        migrations.AlterModelOptions(
            name='preparedcontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tayyor kontent', 'verbose_name_plural': 'Tayyor kontentlar'},
        ),
        migrations.AlterModelOptions(
            name='staffcourseselection',
            options={'ordering': ['-selected_at'], 'verbose_name': "O'qituvchi fan tanlovi", 'verbose_name_plural': "O'qituvchi fan tanlovlari"},
        ),
        migrations.AlterModelOptions(
            name='stafflocationalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Joylashuv ogohlantirishi', 'verbose_name_plural': 'Joylashuv ogohlantirishlari'},
        ),
        migrations.AlterModelOptions(
            name='stafflocationping',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Joylashuv pingi', 'verbose_name_plural': 'Joylashuv pinglari'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Xodim profili', 'verbose_name_plural': 'Xodim profillari'},
        ),
        migrations.AlterModelOptions(
            name='staffscheduleslot',
            options={'ordering': ['owner_key', 'week_phase', 'weekday', 'start_time'], 'verbose_name': 'Xodim jadval sloti', 'verbose_name_plural': 'Xodim jadval slotlari'},
        ),
        migrations.AlterModelOptions(
            name='startupprojectapplication',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Startap arizasi', 'verbose_name_plural': 'Startap arizalari'},
        ),
        migrations.AlterModelOptions(
            name='syllabusdocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Eski syllabus hujjati', 'verbose_name_plural': 'Eski syllabus hujjatlari'},
        ),
        migrations.AlterModelOptions(
            name='topichandout',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Mavzu tarqatmasi', 'verbose_name_plural': 'Mavzu tarqatmalari'},
        ),
        migrations.AlterModelOptions(
            name='topicpresentation',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Mavzu taqdimoti', 'verbose_name_plural': 'Mavzu taqdimotlari'},
        ),
        migrations.RemoveConstraint(
            model_name='livetestsubmission',
            name='uniq_live_test_submission_participant',
        ),
        migrations.RemoveIndex(
            model_name='livetestsession',
            name='core_lts_owner_closed_idx',
        ),
        migrations.RenameIndex(
            model_name='coursesyllabus',
            new_name='core_course_is_acti_582581_idx',
            old_name='core_course_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='devicepairingsession',
            new_name='core_device_status_d1bff8_idx',
            old_name='core_device_status_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='staffcourseselection',
            new_name='core_staffc_owner_k_0dafd5_idx',
            old_name='core_staffc_owner_k_idx',
        ),
        migrations.RenameIndex(
            model_name='topichandout',
            new_name='core_topich_topic_n_bee69e_idx',
            old_name='core_topich_topic_n_0a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='topichandout',
            new_name='core_topich_owner_k_ac9c39_idx',
            old_name='core_topich_owner_k_7c4e91_idx',
        ),
        migrations.RenameIndex(
            model_name='topicpresentation',
            new_name='core_topicp_topic_n_3c45e4_idx',
            old_name='core_topicp_topic_n_0a8f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='topicpresentation',
            new_name='core_topicp_owner_k_ab3fe2_idx',
            old_name='core_topicp_owner_k_7c4e1b_idx',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='participant_kind',
            field=models.CharField(blank=True, choices=[('student', 'Talaba'), ('employee', 'Xodim')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='study_group',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='coursesyllabus',
            name='instruction_language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('en', 'Ingliz'), ('ru', 'Rus')], db_index=True, default='uz', max_length=8),
        ),
        migrations.AlterField(
            model_name='devicepairingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('picked_up', 'Ulangan'), ('expired', 'Muddati tugagan')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='preparedcontent',
            name='kind',
            field=models.CharField(choices=[('lecture', "Ma'ruza"), ('presentation', 'Taqdimot'), ('case', 'Klinik holat'), ('test', 'Test')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='topichandout',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Rasm')], default='pdf', max_length=16),
        ),
    ]
