# Generated by Django 6.0.4 on 2026-07-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_campusbuilding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcourseselection',
            name='variant_label',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
