# Generated by Django 6.0.4 on 2026-07-25 05:00

import core.models
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_backfill_prepared_subject_code'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='SubjectBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('source_archive', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(blank=True, max_length=512, upload_to=core.models.book_upload_to)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='core.academicdepartment')),
            ],
            options={
                'verbose_name': 'Fan darsligi',
                'verbose_name_plural': 'Fan darsliklari',
                'ordering': ['department__sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_chunks', to='core.academicdepartment')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.subjectbook')),
            ],
            options={
                'verbose_name': "Kitob chunk'i",
                'verbose_name_plural': "Kitob chunk'lari",
                'ordering': ['book_id', 'chunk_index'],
                'indexes': [models.Index(fields=['department'], name='core_bookch_departm_2b77f1_idx'), models.Index(fields=['book', 'chunk_index'], name='core_bookch_book_id_5823b1_idx')],
            },
        ),
    ]
